dist: trusty
services:
  - docker
language: go
go:
  - "1.11.x"

before_install:
  - sudo add-apt-repository -y cloud-archive:mitaka
  - sudo apt-get -qq update
  - sudo apt-get install -y qemu libvirt-bin libvirt-dev
  - sudo usermod -a -G libvirtd $USER
  - echo -e "<pool type='dir'>\n<name>default</name>\n<target>\n<path>/pool-default</path>\n</target>\n</pool>" > pool.xml
  - sudo mkdir /pool-default
  - sudo chmod a+rwx /pool-default
  - sudo virsh pool-define pool.xml
  - sudo virsh pool-start default

install:
  - make

# override the custom test script, this would trigger
# also the execution of the unit tests of the vendored
# code
env:
  global:
    - TERRAFORM_LIBVIRT_TEST_DOMAIN_TYPE=qemu
    - TF_ACC=true
    - LIBVIRT_DEFAULT_URI="qemu:///system"

script:
  #- sg libvirtd -c "go test -v ./providers"
  #- sg libvirtd -c "go test -v ./provisioners"
  - make test
  - make vet
  #- make website-test

branches:
  only:
    - master
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
