dist: xenial

sudo: enabled

addons:
  snaps:
    - lxd

services:
  - docker

language: go
go:
  - "1.11.x"

before_install:
  - sudo sh -c 'echo PATH=/snap/bin:$PATH >> /etc/environment';
    sudo sh -c 'lxd activateifneeded';
    sudo sh -c 'lxd waitready';
    sudo sh -c 'lxd init --auto';
    sudo usermod -a -G lxd travis;
    sudo su travis -c 'lxc network set lxdbr0 ipv6.address none'

install:
  - make

env:
  global:
    - TF_ACC=true
    - LC_ALL=C.UTF-8
    - LANG=C.UTF-8

script:
  - make test
  - make vet

branches:
  only:
    - master

after_failure:
  - sudo journalctl -u snapd

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
