dist: xenial

sudo: enabled

services:
  - docker

language: go
go:
  - "1.11.x"

before_install:
  - sudo apt update
  - sudo apt install -y lxd
  - sudo lxd waitready
  - sudo lxd init --auto
  - mkdir -p "$TRAVIS_BUILD_DIR/snaps-cache"
  - sudo usermod -a -G lxd travis;

install:
  - make

env:
  global:
    - TF_ACC=true
    - LC_ALL=C.UTF-8
    - LANG=C.UTF-8

script:
  - make test
  - make vet

branches:
  only:
    - master

after_failure:
  - sudo journalctl -e

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
